name: Build and Push Docker Images
on:
  push:
    branches:
      - main
      - 'release-*'
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push yolov5-prediction
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_prediction
          push: true
          tags: meta1408/streamlit_yolo:yolov5-prediction
      - name: Build and push yolov5-storage
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_storage
          push: true
          tags: meta1408/streamlit_yolo:yolov5-storage
      - name: Build and push yolov5-streamlit
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile_streamlit
          push: true
          tags: meta1408/streamlit_yolo:yolov5-streamlit